export interface postCarClientDTO {
    cd_cliente:      number;
    placa:           string;
    modelo:          string;
    cd_tipo_veiculo: string;
}
// Generated by https://quicktype.io

export interface editClientCarDTO {
    cd_cliente:      number;
    placa:           string;
    modelo:          string;
    cd_tipo_veiculo: string;
    cd_veiculo:      number;
}

export interface deleteClientCarDTO{
    cd_veiculo: number
}

export interface GetTypeCarDTO {
    cd_tipo_veiculo: number;
    descricao:       string;
}

export interface getCarByClientDTO{
    cd_cliente:number
}